
services:
  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tr3
      MYSQL_USER: tr3
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      # Per guardar les dades de forma persistent
      - ./mysql_data:/var/lib/mysql
      # Per crear algunes taules al primer inici
      - ./mysql/dades.sql:/docker-entrypoint-initdb.d/dades.sql
  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

