version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: salma
      MYSQL_USER: usuari
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env 
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3000
    env_file:
      - .env 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  stats-generator:
    build: ./backend/microserveis/stats-service
    restart: always
    depends_on:
      - mysql 

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  logs-microservice:
    build: ./backend/microserveis/mongoDB
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

    depends_on:
      - mongo

volumes:
  mysql_data:
  mongo-data:
